# Numpy

numpy is fast with vectorized operations (linear algebra)




In [2]:
import numpy as np

# create array
a=np.array([1,2,3,4])
print(a)
x=np.array([[1,2],[3,4],[5,6]])
x[2,1]=0
print(x)

[1 2 3 4]
[[1 2]
 [3 4]
 [5 0]]


#### More on creating arrays

In [3]:
a=np.arange(12)
b=np.zeros(3)
c=np.zeros((2,3,4)) # 3-dimensional array
d=np.linspace(1,5,11) # from, to, total number
print(a)
print(b)
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


In [4]:
twobysix=a.reshape(2,6)
print(twobysix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [5]:
sixbytwo=np.arange(12).reshape(6,2)
print(sixbytwo)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


#### Operations

In [6]:
print(twobysix@sixbytwo)
print(sixbytwo@twobysix)

[[110 125]
 [290 341]]
[[  6   7   8   9  10  11]
 [ 18  23  28  33  38  43]
 [ 30  39  48  57  66  75]
 [ 42  55  68  81  94 107]
 [ 54  71  88 105 122 139]
 [ 66  87 108 129 150 171]]


In [7]:
twobysix*twobysix

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121]])

In [8]:
A= np.array([[1,1],[0,1]])
B=np.array([[2,3],[4,1]])

In [9]:
print(A.dot(B))
print(A@B)
print(A+B)
print(A-B)

[[6 4]
 [4 1]]
[[6 4]
 [4 1]]
[[3 4]
 [4 2]]
[[-1 -2]
 [-4  0]]


In [10]:
print(A.dtype)
print(A.dtype.name)

int32
int32


In [13]:
float(A[1,1])=5.2
A

SyntaxError: cannot assign to function call (Temp/ipykernel_8740/4005095819.py, line 1)

In [17]:
B=A.astype(float)
B[1,1]=5.5
B

array([[1. , 1. ],
       [0. , 5.5]])

In [18]:
Z=np.array([0,1], dtype=bool)
Z

array([False,  True])

In [16]:
print(B[Z])
print(B[Z][0])
print(B[Z][0][1])

[[0.  5.5]]
[0.  5.5]
5.5


In [17]:
print(B[Z].mean())
print(B[:,Z].mean())
print(B[:,Z].std())

2.75
3.25
2.25
